major/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
urlpatterns=[
	url(r'^$',views.index,name="index"),
	url(r'^index_aj$',views.index_aj,name="index_aj"),
	url(r'^login$',views.login,name="login"),# Administration Pages
	url(r'^register$',views.register,name="register"),# Administration Pages
	url(r'^reset$',views.reset,name="reset"),# Administration Pages
	url(r'^rabbithole$',views.after_reg,name="after_reg"),# Administration Pages
	url(r'^userinfo$',views.userinfo,name="userinfo"),# Administration Pages
	url(r'^upload$',views.upload,name='upload'),
	url(r'^download$',views.download,name='download'),
	url(r'^download_aj$',views.download_aj,name='download_aj'),
	url(r'^clients/(?P<cid>[0-9]{10})$',views.clients,name="clientpage"),
	url(r'^group$',views.group,name="group"),
	url(r'^transparent$',views.transparent,name="transparent"),
	url(r'^transparent_aj$',views.transparent_aj,name="transparent_aj"),
	url(r'^groupinfo$',views.groupinfo,name="groupinfo"),
	url(r'^group_aj$',views.group_aj,name="group_aj"),
	url(r'^gchat_aj$',views.gchat_aj,name="gchat_aj"),
	url(r'^help$',views.help,name="help"),
	url(r'^termap$',views.termap,name="termap"),
	url(r'^officeuse$',views.officeuse,name='officeuse'),
	url(r'^ajaxofficeuse$',views.ajax_officeuse,name='ajax_officeuse'),
	url(r'^tablebook_aj$',views.tablebook_aj,name='tablebook_aj'),
	url(r'^worldsync$',views.worldsync,name="worldsync"),
	url(r'^reg$',views.reg,name="registration"),
	url(r'^test$',views.testview,name="testview"),
	url(r'^authportal/(?P<job>[a-z]{9})$',views.authportal,name="authportal"),
	url(r'^authset$',views.authset,name="authset"),
	url(r'^authassign$',views.authassign,name="authassign"),
	url(r'^process$',views.process,name="process"),
	url(r'^sys$',views.sys,name="sys"),
	url(r'^search_suggest$',views.search_suggest,name="search_suggest"),
	url(r'^privatemsg$',views.private_msg,name="private_msg"),
	url(r'^privatemsg_aj$',views.privatemsg_aj,name="private_msg_aj"),
	url(r'^userlist$',views.userlist,name="userlist"),
	url(r'^crontab$',views.crontab,name="crontab"),
	url(r'^cssadvlist$',views.cssadvlist,name="cssadvlist"),
	url(r'^cssadvlist_aj$',views.cssadvlist_aj,name="cssadvlist_aj"),
	url(r'^cssadvupload$',views.cssadvupload,name="cssadvupload"),
	url(r'^cssadvjs$',views.cssadvjs,name="cssadvjs"),
	url(r'^cadetail$',views.cadetail,name="cadetail"),
	url(r'^color$',views.color_dial,name="color"),
	url(r'^cajs$',views.cajs,name="cajs"),
	url(r'^arupload$',views.arupload,name="arupload"),
	url(r'^viewclient$',views.viewclient,name="viewclient"),
	url(r'^arreport$',views.arreport,name="arreport"),
	url(r'^arreport_aj$',views.arreport_aj,name="arreport_aj"),
	url(r'^button$',views.button,name="button"),
	url(r'^sqlupdate$',views.sqlupdate,name="sqlupdate"),
]

terminus/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
	url(r'^',include('major.urls')),
    url(r'^admin/', admin.site.urls),
]

major/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

major/forms.py
# -*- coding: utf-8 -*-
from django import forms
from bson.objectid import ObjectId
from bootstrap3_datetime.widgets import DateTimePicker
#from lib import get_db

class rich_form(forms.Form):
	def as_read(self):
		rt=''
		for k,v in self.cleaned_data.iteritems():
			rt+='<tr><td>'
			rt+=str(self.field[k].label)
			rt+='</td><td>'
			if type(v)==list:
				for ite in v:
					rt+=str(ite)
			else:
				rt+=str(v)
			rt+='</td></tr>'
	def set_choices(self,fieldname,newlist):
		self.fields[fieldname].choices=newlist

class email_login(forms.Form):
	email=forms.EmailField(
		label=u'公司邮箱',
		#strip=True,
		required=True,
		)
	password=forms.CharField(
		widget=forms.widgets.PasswordInput,
		label=u'密码',
		required=True,
		)
class clientset(forms.Form):
	client=forms.IntegerField(
		label=u'客户编码',
		widget=forms.widgets.TextInput,
		)
	client_cn=forms.CharField(
		label=u'客户名称',
		strip=True,
		)
	sales=forms.CharField(
		label=u'销售',
		strip=True,
		required=False,
		)
	cre_term=forms.CharField(
		label=u'账期',
		strip=True,
		required=False,
		)
class userset_extra(forms.Form):
	manager=forms.CharField(
		label=u'直属领导',
		strip=True,
		required=False,
		max_length=30,
		)
	department=forms.TypedChoiceField(
		label=u'部门',
		choices=[
		['finance',u'财务部'],
		['it',u'资讯科技部'],
		],
		)
	ext=forms.CharField(
		label=u'电话/分机号',
		strip=True,
		required=False,
		max_length=20,
		)
from django.template import loader
class tagform:
	def __init__(self,tagfield,inputdict=None):
		if inputdict:
			self.inputdict=inputdict
		else:
			self.inputdict={}
		self.tagfield=tagfield
		self.update_cross_pull={}

	def inputdict_process(self):
		if self.inputdict:
			for item in self.inputdict:
				item.update({"id":item.__getitem__("_id")})
				item.update({"tagname":item[self.tagfield]})
				item.update({"jpack":{
						"update_condi":{
							"_id":str(item.__getitem__("_id"))
							},
						"update_cross_pull":{
							"$pull":self.update_cross_pull
							},
						}
					})
		else:
			pass

	def tagtile(self,template_dir="tagtile.html"):
		self.inputdict_process()
		template=loader.get_template(template_dir)
		context={
		"taglist":self.inputdict,
		"tagfield":self.tagfield,
		}
		return template.render(context)


class uploadset(rich_form):
	schema=forms.TypedChoiceField(
		label=u'空表头',
		initial="ignore",
		widget=forms.widgets.RadioSelect,
		choices=[
		["ignore",u'忽略'],
		["match",u'匹配'],
		["upsert",u'插入/更新'],
		["push",u'推入数组']
		],
		)
#	dbfield=forms.CharField(
#		label=u'数据库字段',
#		required=False,
#		)

class fm_officeuse(rich_form):
	stburl=forms.CharField(
		label=u'链接',
		max_length=100,
		required=False,
		widget=forms.TextInput(attrs={"placeholder":u'贴入史泰博官网的产品链接',},)
		)

class fm_officeuse_proid(fm_officeuse):
	pro_id=forms.CharField()

class office_use_detail(rich_form):
	processid=forms.CharField(
		widget=forms.widgets.HiddenInput,
		required=False,
	)
	pic_src=forms.CharField(
		widget=forms.widgets.HiddenInput,
		required=False,
	)
	brandname=forms.CharField(
		widget=forms.widgets.HiddenInput,
		required=False,
	)
	itemname=forms.CharField(
		label=u'物品名称',
		max_length=100,
		)
	price=forms.DecimalField(
		label=u'单价',
		min_value=0,
		)
	pro_id=forms.CharField(
		label=u'官网编号',
		)
	qtt=forms.IntegerField(
		label=u'数量',
		required=False,
		initial=1,
		min_value=1,
		)
#	pic_src=forms.CharField(
#		required=False,
#		)

class upload_input(rich_form):
	fname=forms.CharField(
		label=u'上传流程',
		max_length=50,
		)
	fileup=forms.FileField(
		label=u'文件地址',
		)
class upload_hidden(rich_form):
	md=forms.CharField(
		initial="upload",
		widget=forms.widgets.HiddenInput,
		)

class auth_default(rich_form):
	r=forms.TypedChoiceField(
		label=u'Read',
		initial=1,
		widget=forms.widgets.RadioSelect,
		choices=[
		[1,u'Yes'],
		[0,u'No'],
		])
	w=forms.TypedChoiceField(
		label=u'Write',
		initial=1,
		widget=forms.widgets.RadioSelect,
		choices=[
		[1,u'Yes'],
		[0,u'No'],
		])
	# Write authorization won't work after the approval was granted
#	s=forms.TypedChoiceField(
#		label=u'Super',
#		initial=0,
#		widget=forms.widgets.RadioSelect,
#		choices=[
#		[1,u'Yes'],
#		[0,u'No'],
#		])
	# User can send emails to super to ask their grand

class user_auth_apply(auth_default):
	"""
	User can apply for user authorization
	"""
	taskname=forms.CharField(
		widget=forms.widgets.HiddenInput,
		)
	process=forms.CharField(
		initial=u"auth",
		widget=forms.widgets.HiddenInput,
	)
	#processid
	apid=forms.CharField(
		widget=forms.widgets.HiddenInput,
		)
	#need to inputa list of super assigner
# co	supers=forms.TypedChoiceField(
# co		label=u'Role Assigner',
# co		widget=forms.widgets.RadioSelect,
# co		)
# co	remark=forms.CharField(
# co		label=u"Remark",
# co		max_length=500,
# co		required=False,
# co		)
class task_write(auth_default):
	s=None
	settype=forms.CharField(
		initial=u"settask",
		widget=forms.widgets.HiddenInput,
	)
	taskname=forms.CharField(
		label=u'Task Name',
		max_length=50,
		)
class page_selector_form(rich_form):
	page=forms.IntegerField(
		label=u"Page",
		initial=1,
		max_value=2,
		min_value=1,
		)
class table_book_filter(rich_form):
	fil_applier=forms.CharField(
		label=u'申请人',
		)

class transparent_set(rich_form):
	task=forms.TypedChoiceField(
		label=u'事务',
		initial="officeuse",
		widget=forms.widgets.RadioSelect,
		choices=[
		["officeuse",u'行政领用'],
		],
		)
	datestart=forms.DateField(
		widget=DateTimePicker(options={"format": "YYYY-MM-DD","pickTime":False}),
		label=u'开始日期',
		required=False,
		)
	dateend=forms.DateField(
		widget=DateTimePicker(options={"format": "YYYY-MM-DD","pickTime":False}),
		label=u'结束日期',
		required=False,
		)
	prospect=forms.TypedChoiceField(
		label=u'查看方式',
		initial="sf",
		widget=forms.widgets.RadioSelect,
		choices=[
		["sf",u'只看自己'],# stands for self
		["dp",u'我的部门'],# stands for department
		],
		)
class download_range(rich_form):
	datestart=forms.DateField(
		widget=DateTimePicker(options={"format": "YYYY-MM-DD","pickTime":False}),
		label=u'开始日期',
		required=False,
		)
	dateend=forms.DateField(
		widget=DateTimePicker(options={"format": "YYYY-MM-DD","pickTime":False}),
		label=u'结束日期',
		required=False,
		)
	taskname=forms.TypedChoiceField(
		label=u'申请种类',
		choices=[
		['officeuse',u'行政领用'],
		['auth',u'权限申请'],
		],
		)
class process_status(rich_form):
	pstatus=forms.TypedChoiceField(
		required=True,
		label=u'表单状态',
		initial=["finished","done"],
		widget=forms.widgets.CheckboxSelectMultiple,
		choices=[
	["finished",u"审批成功"],
	["inprogress",u"审批中"],
	["edit",u"申请人修改"],
	["revoked",u'自行撤回'],
	["done",u"执行完成"],
	["dead",u'申请失败'],
		])
class loadback(rich_form):
	md=forms.CharField(
		widget=forms.widgets.HiddenInput,
		required=False,
		initial='loadback',
	)
	taskname=forms.TypedChoiceField(
		label=u'申请种类',
		choices=[
		['officeuse',u'行政领用'],
		['auth',u'权限申请'],
		],
		)
	lbfile=forms.FileField(
		label=u'文件地址',
		)
class groupinfo_form(rich_form):
	groupname=forms.CharField(
		required=True,
		label=u'团队英文名',
		max_length=20,
		)
	cnname=forms.CharField(
		required=True,
		label=u'团队中文名',
		max_length=20,
		)
	groupid=forms.CharField(
		widget=forms.widgets.HiddenInput,
		required=False,
	)
class cssupload(rich_form):
	csstask=forms.TypedChoiceField(
		label=u'上传任务',
		required=True,
		choices=[
		['contact',u'联系方式'],
		['user',u'用户设置'],
		['costcenter',u'成本中心'],
		['addr',u'新增地址'],
		],
		)
	fileup=forms.FileField(
		label=u'文件',
		)

class cssadv_list(rich_form):
	datestart=forms.DateField(
		widget=DateTimePicker(options={"format": "YYYY-MM-DD","pickTime":False}),
		label=u'开始日期',
		required=False,
		)
	dateend=forms.DateField(
		widget=DateTimePicker(options={"format": "YYYY-MM-DD","pickTime":False}),
		label=u'结束日期',
		required=False,
		)
	csstask=forms.TypedChoiceField(
		label=u'上传任务',
		required=True,
		choices=[
		['contact',u'联系方式'],
		['user',u'用户设置'],
		['costcenter',u'成本中心'],
		['addr',u'新增地址'],
		],
		)
	status=forms.TypedChoiceField(
		label=u'处理状态',
		required=True,
		choices=[
		['0',u'未处理'],
		['1',u'已完成'],
		['-1',u'已删除'],
		],
		)

class ar_upload(rich_form):
	formtype=forms.TypedChoiceField(
		label=u'上传文件',
		required=True,
		choices=[
		['overdue',u'逾期报表'],
		['arbd',u'AR Breakdown'],
		['cplist',u'项目清单'],
		],
		)
	fileup=forms.FileField(
		label=u'文件',
		)
	exdate=forms.DateField(
		widget=DateTimePicker(options={"format": "YYYY-MM-DD","pickTime":False}),
		label=u'导出日期',
		required=True,
		)
class od_upload(rich_form):
	formtype=forms.TypedChoiceField(
		label=u'上传文件',
		required=True,
		choices=[
		['overdue',u'逾期报表'],
		],
		)
	fileup=forms.FileField(
		label=u'文件',
		)

major/share/upgrade/forms.py
# -*- coding: utf-8 -*-
from django import forms
from bson.objectid import ObjectId
#from lib import get_db

class rich_form(forms.Form):
	def as_read(self):
		rt=''
		for k,v in self.cleaned_data.iteritems():
			rt+='<tr><td>'
			rt+=str(self.field[k].label)
			rt+='</td><td>'
			if type(v)==list:
				for ite in v:
					rt+=str(ite)
			else:
				rt+=str(v)
			rt+='</td></tr>'
	def set_choices(self,fieldname,newlist):
		self.fields[fieldname].choices=newlist

# class email_login(forms.Form):
# 	email=forms.EmailField(
# 		label=u'公司邮箱',
# 		strip=True,
# 		required=True,
# 		)
# 	password=forms.CharField(
# 		widget=forms.widgets.PasswordInput,
# 		label=u'密码',
# 		required=True,
# 		)
#	department=forms.TypedChoiceField(
#		label=u'部门',
#		choices=[
#		['finance',u'财务部'],
#		['it',u'资讯科技部'],
#		],
#		)
#	taskname=forms.CharField(
#		widget=forms.widgets.HiddenInput,
#		)
#	fileup=forms.FileField(
#		label=u'文件',
#		)

major/share/upgrade/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from config.st import gen
from share.lib.basic import get_db,adm

# Create your views here.
# Administration pages ===========
admcls=adm(gen)
# admcls.f_save_request=save_request
# admcls.f_userbar=userbar
# admcls.i_userset_extra=userset_extra
def login(request):
	rtway=admcls.login(request)
	return eval(rtway["w"])(rtway["v"])
def register(request):
	rtway=admcls.register(request)
	return eval(rtway["w"])(rtway["v"])
def reset(request):
	rtway=admcls.reset(request)
	return eval(rtway["w"])(rtway["v"])
def userinfo(request):
	rtway=admcls.userinfo(request)
	return eval(rtway["w"])(rtway["v"])
def after_reg(request):
	rtway=admcls.after_reg(request)
	return eval(rtway["w"])(rtway["v"])
# Administration Pages ===========

major/templates/ar/arreport.html
<!DOCTYPE html>
<html>
<head>
	<title>AR Report - Monthly (Terminus II)</title>
</head>
<body>
{{userb}}

<div>
	{{pivot|safe}}
</div>
</body>
</html>

major/templates/ar/arupload.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type='text/javascript' src='{% static "js/bootstrap.js" %}'></script>
	<style type="text/css">
		@import url('{%static "css/bootstrap.css"%}');
		@import url('{%static "css/bootstrap_theme.css"%}');
		body
		{
			margin:0px;
			padding:0px;
			background-color:#FFF;
			color:#000;
			font-family:微软雅黑,Tahoma,Arial;
			text-align:center;
		}
		#col_left
		{
			width:400px;
			display: inline-block;
			vertical-align: top;
			text-align: left;
			padding:10px;
		}
		#id_formtype
		{
			padding:5px;
			border:1px solid #CCC;
			border-radius:5px;
			width:180px;
			background-color: #FFF;
		}
		#ar_upload_table
		{
			font-family:微软雅黑,Tahoma,Arial;
		}
		h2
		{
			font-family:微软雅黑,Tahoma,Arial;
			font-weight: 100;
		}
		.red_text
		{
			color:red;
		}
		#col_right
		{
			display: inline-block;
			vertical-align: top;
			width:600px;
			overflow: scroll;
			margin:20px;
		}
		.dataframe th
		{
			white-space: nowrap;
			background-color: #4682B4;
			color:#FFF;
			border:0px solid #FFF;
			padding:2px 5px;
		}
		.dataframe td
		{
			white-space: nowrap;
			border:0px solid #FFF;
			padding:2px 5px;
		}
		button
		{
			padding:10px 20px;
			background-color: #4682B4;
			color:#FFF;
			border-radius:5px;
			border:0px solid #FFF;
		}
	</style>
	<title>应收账款逾期报表上传 Account Receivable Overdue Report Up load --Terminus II</title>
</head>
<body>
{{userb}}
<div id="col_left">
{{backmsg}}
{{fm.media}}
<h2>应收账款逾期报表上传</h2>
<h2>Account Receivable Overdue Report UPload</h2>
<br>
<div>上传人:<span class="red_text">{{cnname}}</span></div>
<br>
<div>

<table id='ar_upload_table'>
<form method='POST' enctype='multipart/form-data' action="/arupload">
	{% for field in fm.visible_fields %}
            <div id="div_{{ field.html_name }}"
                 class="form-group{% if field.errors %} has-error{% endif %}">
                {{ field.label_tag }}
                {{ field }}
                <div class="text-muted pull-right">
                    <small>{{ field.help_text }}</small>
                </div>
                <div class="help-block">
                    {{ field.errors }}
                </div>
            </div>
	{% endfor %}
	{% csrf_token %}
	<tr>
		<td colspan="2" style="text-align:center;"><button id='upload_btn'>上传</button></td>
	</tr>
</form>
</table>
<br>
<br>

<h3>Controls</h3>
<br>
<button id='cplist2bu'>CP List</button>
<button id='cplist2bu_uc'>CP List Cash</button>
<div id='control_result'></div>
</div>

</div>

<div id='col_right'>
	{{preview|safe}}
</div>

</body>
<script type="text/javascript">
$(document).ready(function page_loaded(){
	$("#cplist2bu").click(function click_cp2bu(){
		$("#control_result").html("Processing...")
		var aj={};
		aj.btn="match_cplist";
		$.ajax({
			url:"button",
			async:true,
			data:aj,
			method:"GET",
			success:function cplist2bu_aj_success(data){
				if(data=="ok")
				{
				$("#control_result").html("Match Successfully")
				}
			}
		})
	})
	$("#cplist2bu_uc").click(function click_cp2bu(){
		$("#control_result").html("Processing...")
		var aj={};
		aj.btn="match_cplist_uc";
		$.ajax({
			url:"button",
			async:true,
			data:aj,
			method:"GET",
			success:function cplist2bu_aj_success(data){
				if(data=="ok")
				{
				$("#control_result").html("Match Successfully")
				}
			}
		})
	})
})
</script>
</html>

major/templates/ar/client.html
<!DOCTYPE html>
<html>
<head>
<style type="text/css">
	body
	{
		padding: 0px;
		margin: 0px;
 		font-family:微软雅黑,Tahoma,Arial;
 		background-color: #FFF;
	}
	#page_body
	{
		padding:20px 90px;
	}
	#client_info_table th
	{
		background-color:#4682B4;
		color:#FFF;
		font-weight: 300;
		width:450px;
		font-size:20px;
	}
	#client_info_table td
	{
		font-weight: 100;
		padding:5px;
		font-size:18px;
	}
	#company_name
	{
		font-weight:200;
		font-size:60px;
	}
</style>
	<title>客户信息浏览-[{{arclient.cid}}]-Terminus Mark II</title>
</head>
<body>
{{userb}}
<div id="page_body">
	<h3 id="company_name">
		{% for cname in arclient.cnm %}
		{{cname}}<br>
		{% endfor %}
	</h3>
	<div id="left_sec">
		<div id='client_info_tag'>
		<table id="client_info_table">
		{% if arclient.term %}
		<tr><th>账期</th></tr>
		<tr><td>	{% for term in arclient.term %}
				{{term}}<br>
				{% endfor %}</td></tr>
		{% endif %}
		{% if arclient.city %}
		<tr><th>地区</th></tr>
		<tr><td>	{% for city in arclient.city %}
				{{city}}<br>
				{% endfor %}</td></tr>
		{% endif %}
		{% if arclient.city %}
		<tr><th>发票抬头</th></tr>
		<tr><td>	{% for itt in arclient.itt %}
				{{itt}}<br>
				{% endfor %}</td></tr>
		{% endif %}
		{% if arclient.ctyp %}
		<tr><th>客户类型</th></tr>
		<tr><td>	{% for ctyp in arclient.ctyp %}
				{{ctyp}}<br>
				{% endfor %}</td></tr>
		{% endif %}
		</table>
		</div>
	</div>
</div>
</body>
</html>

major/templates/ar/odupload.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type='text/javascript' src='{% static "js/bootstrap.js" %}'></script>
	<style type="text/css">
		@import url('{%static "css/bootstrap.css"%}');
		@import url('{%static "css/bootstrap_theme.css"%}');
		body
		{
			margin:0px;
			padding:0px;
			background-color:#FFF;
			color:#000;
			font-family:微软雅黑,Tahoma,Arial;
			text-align:center;
		}
		#col_left
		{
			width:400px;
			display: inline-block;
			vertical-align: top;
			text-align: left;
			padding:10px;
		}
		#id_formtype
		{
			padding:5px;
			border:1px solid #CCC;
			border-radius:5px;
			width:180px;
			background-color: #FFF;
		}
		#ar_upload_table
		{
			font-family:微软雅黑,Tahoma,Arial;
		}
		h2
		{
			font-family:微软雅黑,Tahoma,Arial;
			font-weight: 100;
		}
		.red_text
		{
			color:red;
		}
		#col_right
		{
			display: inline-block;
			vertical-align: top;
			width:600px;
			overflow: scroll;
			margin:20px;
		}
		.dataframe th
		{
			white-space: nowrap;
			background-color: #4682B4;
			color:#FFF;
			border:0px solid #FFF;
			padding:2px 5px;
		}
		.dataframe td
		{
			white-space: nowrap;
			border:0px solid #FFF;
			padding:2px 5px;
		}
		button
		{
			padding:10px 20px;
			background-color: #4682B4;
			color:#FFF;
			border-radius:5px;
			border:0px solid #FFF;
		}
	</style>
	<title>应收账款逾期报表上传 Account Receivable Overdue Report Up load --Terminus II</title>
</head>
<body>
{{userb}}
<div id="col_left">
{{backmsg}}
{{fm.media}}
<h2>应收账款逾期报表上传</h2>
<h2>Account Receivable Overdue Report UPload</h2>
<br>
<div>上传人:<span class="red_text">{{cnname}}</span></div>
<br>
<div>

<table id='ar_upload_table'>
<form method='POST' enctype='multipart/form-data' action="/sqlupdate">
	{% for field in fm.visible_fields %}
            <div id="div_{{ field.html_name }}"
                 class="form-group{% if field.errors %} has-error{% endif %}">
                {{ field.label_tag }}
                {{ field }}
                <div class="text-muted pull-right">
                    <small>{{ field.help_text }}</small>
                </div>
                <div class="help-block">
                    {{ field.errors }}
                </div>
            </div>
	{% endfor %}
	{% csrf_token %}
	<tr>
		<td colspan="2" style="text-align:center;"><button id='upload_btn'>上传</button></td>
	</tr>
</form>
</table>
<br>
<br>

</div>

</div>

<div id='col_right'>
	{{preview|safe}}
</div>

</body>

</html>